/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp Chat.xml -i Message.h -p ChatInterface
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */
 
#ifndef CHATINTERFACE_H_1270658265
#define CHATINTERFACE_H_1270658265
 
#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "Message.h"
 
/*
 * Proxy class for interface demo.Chat
 */
class DemoChatInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "demo.Chat"; }
 
public:
    DemoChatInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);
 
    ~DemoChatInterface();
 
    Q_PROPERTY(QStringList users READ users)
    inline QStringList users() const
    { return qvariant_cast< QStringList >(property("users")); }
 
public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> addUser(const QString &user)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(user);
        return asyncCallWithArgumentList(QLatin1String("addUser"), argumentList);
    }
 
    inline QDBusPendingReply<> removeUser(const QString &user)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(user);
        return asyncCallWithArgumentList(QLatin1String("removeUser"), argumentList);
    }
 
    inline QDBusPendingReply<> sendMessage(Message message)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(message);
        return asyncCallWithArgumentList(QLatin1String("sendMessage"), argumentList);
    }
 
Q_SIGNALS: // SIGNALS
    void messageSent(Message message);
    void userAdded(const QString &user);
    void userRemoved(const QString &user);
};
 
namespace demo {
  typedef ::DemoChatInterface Chat;
}
#endif
